### ISSUE TITLE
Have a question about the config.

### ISSUE THREAD

**Issue by mandal4** [WuShuang1998/MFDC#1]
Thanks for nice paper and source code. 
Could you tell me what the 'removevoc' stands for in the fine-tuning config file? 
`removevoc_2007_trainval_allx_2shot_seedx`

I have well understood FSOD benchmark. Does it have any difference with data setting of {TFA, DeFRCN}?.

**Comment by WuShuang1998** [comment]
Thanks for your interest!
'removevoc' means that we remove the K-shot base samples from the balanced datasets for fine-tuning.
https://github.com/WuShuang1998/MFDC/blob/972890549af096e7f1a20f60c61a495c549515a1/defrcn/data/meta_voc.py#L22
https://github.com/WuShuang1998/MFDC/blob/972890549af096e7f1a20f60c61a495c549515a1/defrcn/data/meta_voc.py#L31-L33
Instead, we fine-tune the detector with abundant base samples used in the first stage, which is the difference with data setting of TFA and DeFRCN.

**Comment by mandal4** [comment]
Thanks.
