### ISSUE TITLE
Why the different number of images on inference between MDFC and DeFRCN?

### ISSUE THREAD

**Issue by ZhiXianZ** [WuShuang1998/MFDC#2]
MDFC inference log: defrcn.evaluation.evaluator INFO: Start inference on 4952 images
But, DeFRCN inference log (author uploaded): defrcn.evaluation.evaluator INFO: Start inference on 619 images
Thanks and forward to your reply.

**Comment by WuShuang1998** [comment]
Thanks for your attention!
It is possible that you only use single GPU for inference while the authors of DeFRCN use 8.
Please provide more information to let me find the BUG.
