### ISSUE TITLE
Question about queue update

### ISSUE THREAD

**Issue by vineetrshenoy** [WuShuang1998/MFDC#6]
I am running the code during novel fine-tuning on VOC split 1, 1-shot seed 0. During the memory bank update, it seems like the memory bank is updating more samples than there are in the novel set. See below at the debugging output

![mfdc_question](https://user-images.githubusercontent.com/5201109/221696954-4727e90d-7658-4f58-9b71-89abf03c649e.png)

As you can see, the `uniq_c` indices are `[0, 9, 10, 17, 18]`. The novel indices correspond to `[15, 16, 17, 18, 19]`. For index `17`, `features_c_s` is of shape `[26, 2048]`. This seems to violate the 1-shot scenario.

I may be mis-understanding something. What is happening here?

**Comment by WuShuang1998** [comment]
Hi, `features_c_s` indeed denotes the number of `proposal features` for each class. Any region proposals with `IoU > threshold` for an object cound be an element of `features_c_s`, so it's normal for the length of `features_c_s` to be greater than K under K-shot setting.

**Comment by vineetrshenoy** [comment]
Sorry for the late reply -- thanks, this makes sense. I am closing the issue.
